// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateMessageRequest struct {
	Rid       uint64 `protobuf:"varint,1,opt,name=Rid,json=rid" json:"Rid,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	SessionId uint64 `protobuf:"varint,11,opt,name=SessionId,json=sessionId" json:"SessionId,omitempty"`
	Type      uint32 `protobuf:"varint,12,opt,name=Type,json=type" json:"Type,omitempty"`
	Content   string `protobuf:"bytes,13,opt,name=Content,json=content" json:"Content,omitempty"`
	Id        string `protobuf:"bytes,14,opt,name=Id,json=id" json:"Id,omitempty"`
}

func (m *CreateMessageRequest) Reset()                    { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()               {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CreateMessageRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateMessageRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CreateMessageRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateMessageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateMessageResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *CreateMessageResponse) Reset()                    { *m = CreateMessageResponse{} }
func (m *CreateMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageResponse) ProtoMessage()               {}
func (*CreateMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateMessageResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateMessageResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMessageRequest)(nil), "pb.CreateMessageRequest")
	proto.RegisterType((*CreateMessageResponse)(nil), "pb.CreateMessageResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x4e, 0xc3, 0x40,
	0x0c, 0x86, 0x75, 0x49, 0x94, 0x2a, 0x86, 0x54, 0xc8, 0x02, 0xe4, 0x81, 0x21, 0xea, 0x94, 0x89,
	0x85, 0x47, 0xe8, 0x94, 0x81, 0x81, 0x03, 0x1e, 0xa0, 0x8d, 0x2d, 0x74, 0x03, 0x77, 0xc7, 0xf9,
	0x3a, 0xf4, 0x5d, 0x78, 0x58, 0x94, 0x0b, 0x0c, 0x74, 0xfb, 0xff, 0xcf, 0x96, 0xf5, 0x19, 0xfa,
	0x4f, 0x51, 0x3d, 0x7c, 0xc8, 0x63, 0x4c, 0x21, 0x07, 0xac, 0xe2, 0x71, 0xf7, 0x6d, 0xe0, 0x76,
	0x9f, 0xe4, 0x90, 0xe5, 0x79, 0x9d, 0x59, 0xf9, 0x3a, 0x89, 0x66, 0xbc, 0x81, 0xda, 0x3a, 0x26,
	0x33, 0x98, 0xb1, 0xb1, 0x75, 0x72, 0x8c, 0xf7, 0xd0, 0xbe, 0xab, 0xa4, 0x89, 0xa9, 0x1a, 0xcc,
	0xd8, 0xd9, 0xf6, 0x54, 0x1a, 0x3e, 0x40, 0xf7, 0x2a, 0xaa, 0x2e, 0xf8, 0x89, 0xe9, 0xaa, 0xec,
	0x77, 0xfa, 0x07, 0x10, 0xa1, 0x79, 0x3b, 0x47, 0xa1, 0xeb, 0xc1, 0x8c, 0xbd, 0x6d, 0xf2, 0x39,
	0x0a, 0x12, 0x6c, 0xf6, 0xc1, 0x67, 0xf1, 0x99, 0xfa, 0x72, 0x6a, 0x33, 0xaf, 0x15, 0xb7, 0x50,
	0x4d, 0x4c, 0xdb, 0x02, 0x2b, 0xc7, 0xbb, 0x17, 0xb8, 0xbb, 0xb0, 0xd3, 0x18, 0xbc, 0xca, 0xa2,
	0x97, 0xfe, 0xeb, 0x21, 0x34, 0x73, 0x60, 0xf9, 0x95, 0x2b, 0x79, 0x61, 0x2c, 0x3a, 0x53, 0xbd,
	0xb2, 0x25, 0x1f, 0xdb, 0xf2, 0xfc, 0xd3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x30, 0x06,
	0x6e, 0x0d, 0x01, 0x00, 0x00,
}
