// Code generated by protoc-gen-go.
// source: sync.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 同步消息
type SyncMessage struct {
	Type       int32  `protobuf:"varint,11,opt,name=type" json:"type,omitempty"`
	Id         string `protobuf:"bytes,12,opt,name=Id,json=id" json:"Id,omitempty"`
	SessionId  uint64 `protobuf:"varint,13,opt,name=SessionId,json=sessionId" json:"SessionId,omitempty"`
	UserId     string `protobuf:"bytes,14,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	Content    string `protobuf:"bytes,15,opt,name=Content,json=content" json:"Content,omitempty"`
	SyncKey    uint64 `protobuf:"varint,16,opt,name=SyncKey,json=syncKey" json:"SyncKey,omitempty"`
	CreateTime int64  `protobuf:"varint,17,opt,name=CreateTime,json=createTime" json:"CreateTime,omitempty"`
}

func (m *SyncMessage) Reset()                    { *m = SyncMessage{} }
func (m *SyncMessage) String() string            { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()               {}
func (*SyncMessage) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *SyncMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SyncMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SyncMessage) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SyncMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SyncMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SyncMessage) GetSyncKey() uint64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

func (m *SyncMessage) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type SyncFinInform struct {
	SyncKey uint64 `protobuf:"varint,11,opt,name=SyncKey,json=syncKey" json:"SyncKey,omitempty"`
}

func (m *SyncFinInform) Reset()                    { *m = SyncFinInform{} }
func (m *SyncFinInform) String() string            { return proto.CompactTextString(m) }
func (*SyncFinInform) ProtoMessage()               {}
func (*SyncFinInform) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *SyncFinInform) GetSyncKey() uint64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

type SyncFinResponse struct {
	SyncKey uint64 `protobuf:"varint,11,opt,name=SyncKey,json=syncKey" json:"SyncKey,omitempty"`
}

func (m *SyncFinResponse) Reset()                    { *m = SyncFinResponse{} }
func (m *SyncFinResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncFinResponse) ProtoMessage()               {}
func (*SyncFinResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *SyncFinResponse) GetSyncKey() uint64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

func init() {
	proto.RegisterType((*SyncMessage)(nil), "pb.SyncMessage")
	proto.RegisterType((*SyncFinInform)(nil), "pb.SyncFinInform")
	proto.RegisterType((*SyncFinResponse)(nil), "pb.SyncFinResponse")
}

func init() { proto.RegisterFile("sync.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xd9, 0x58, 0x13, 0x32, 0xb1, 0xad, 0xce, 0x41, 0xe6, 0x20, 0x12, 0x72, 0x8a, 0x08,
	0x5e, 0x7c, 0x84, 0x82, 0x10, 0xc4, 0xcb, 0x56, 0x1f, 0xa0, 0x4d, 0x46, 0xc9, 0xa1, 0xb3, 0x61,
	0x67, 0x3d, 0xec, 0xb3, 0xf9, 0x72, 0x92, 0xad, 0x8a, 0x1e, 0xbc, 0xed, 0xff, 0xeb, 0xc7, 0x32,
	0x00, 0x1a, 0xa5, 0xbf, 0x9b, 0xbc, 0x0b, 0x0e, 0xb3, 0x69, 0xdf, 0x7c, 0x18, 0xa8, 0xb6, 0x51,
	0xfa, 0x27, 0x56, 0xdd, 0xbd, 0x31, 0x22, 0x2c, 0x42, 0x9c, 0x98, 0xaa, 0xda, 0xb4, 0xa7, 0x36,
	0xbd, 0x71, 0x05, 0x59, 0x37, 0xd0, 0x59, 0x6d, 0xda, 0xd2, 0x66, 0xe3, 0x80, 0x57, 0x50, 0x6e,
	0x59, 0x75, 0x74, 0xd2, 0x0d, 0xb4, 0xac, 0x4d, 0xbb, 0xb0, 0xa5, 0x7e, 0x1b, 0x78, 0x09, 0xf9,
	0x8b, 0xb2, 0xef, 0x06, 0x5a, 0xa5, 0x45, 0xfe, 0x9e, 0x14, 0x12, 0x14, 0x1b, 0x27, 0x81, 0x25,
	0xd0, 0x3a, 0x05, 0x45, 0x7f, 0x94, 0x73, 0x32, 0x7f, 0xe1, 0x91, 0x23, 0x9d, 0x27, 0x5a, 0xa1,
	0x47, 0x89, 0xd7, 0x00, 0x1b, 0xcf, 0xbb, 0xc0, 0xcf, 0xe3, 0x81, 0xe9, 0xa2, 0x36, 0xed, 0x89,
	0x85, 0xfe, 0xc7, 0x69, 0x6e, 0x60, 0x39, 0x2f, 0x1f, 0x46, 0xe9, 0xe4, 0xd5, 0xf9, 0xc3, 0x6f,
	0x54, 0xf5, 0x07, 0xd5, 0xdc, 0xc2, 0xfa, 0xab, 0x6a, 0x59, 0x27, 0x27, 0xca, 0xff, 0x97, 0xf7,
	0x79, 0x3a, 0xd0, 0xfd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x3f, 0x01, 0x74, 0x2e, 0x01,
	0x00, 0x00,
}
