// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	RpcInfo
	RpcRequest
	RpcResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RpcInfo struct {
	ConnId uint64 `protobuf:"varint,1,opt,name=ConnId" json:"ConnId,omitempty"`
}

func (m *RpcInfo) Reset()                    { *m = RpcInfo{} }
func (m *RpcInfo) String() string            { return proto.CompactTextString(m) }
func (*RpcInfo) ProtoMessage()               {}
func (*RpcInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RpcInfo) GetConnId() uint64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

type RpcRequest struct {
	RpcInfo     *RpcInfo `protobuf:"bytes,1,opt,name=RpcInfo" json:"RpcInfo,omitempty"`
	MessageType uint32   `protobuf:"varint,11,opt,name=MessageType" json:"MessageType,omitempty"`
	ProtoBuf    []byte   `protobuf:"bytes,12,opt,name=ProtoBuf,proto3" json:"ProtoBuf,omitempty"`
}

func (m *RpcRequest) Reset()                    { *m = RpcRequest{} }
func (m *RpcRequest) String() string            { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()               {}
func (*RpcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RpcRequest) GetRpcInfo() *RpcInfo {
	if m != nil {
		return m.RpcInfo
	}
	return nil
}

func (m *RpcRequest) GetMessageType() uint32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcRequest) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

type RpcResponse struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
}

func (m *RpcResponse) Reset()                    { *m = RpcResponse{} }
func (m *RpcResponse) String() string            { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()               {}
func (*RpcResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RpcResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RpcResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcInfo)(nil), "pb.RpcInfo")
	proto.RegisterType((*RpcRequest)(nil), "pb.RpcRequest")
	proto.RegisterType((*RpcResponse)(nil), "pb.RpcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rpc service

type RpcClient interface {
	// Sends a greeting
	Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error)
}

type rpcClient struct {
	cc *grpc.ClientConn
}

func NewRpcClient(cc *grpc.ClientConn) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error) {
	out := new(RpcResponse)
	err := grpc.Invoke(ctx, "/pb.Rpc/Rpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rpc service

type RpcServer interface {
	// Sends a greeting
	Rpc(context.Context, *RpcRequest) (*RpcResponse, error)
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_Rpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Rpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Rpc/Rpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Rpc(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rpc",
			Handler:    _Rpc_Rpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0xcd, 0xba, 0xac, 0xee, 0xcb, 0xaa, 0x90, 0x83, 0x84, 0x3d, 0xc5, 0x80, 0x90, 0x53,
	0x85, 0x15, 0xff, 0x80, 0x9e, 0xf6, 0x20, 0xc8, 0xc3, 0x3f, 0x60, 0xd3, 0x57, 0x6f, 0xc9, 0x6b,
	0xd3, 0x1e, 0xfc, 0xf7, 0xd2, 0x34, 0x84, 0x3d, 0x65, 0xe6, 0x23, 0x99, 0x19, 0x02, 0xfb, 0x91,
	0x7d, 0xc3, 0x63, 0x9c, 0xa2, 0xda, 0x70, 0x6b, 0x9f, 0xe0, 0x06, 0xd9, 0x9f, 0x43, 0x1f, 0xd5,
	0x23, 0xec, 0x3e, 0x62, 0x08, 0xe7, 0x4e, 0x0b, 0x23, 0xdc, 0x16, 0x8b, 0xb3, 0x03, 0x00, 0xb2,
	0x47, 0x1a, 0x66, 0x4a, 0x93, 0x7a, 0xae, 0x0f, 0xf2, 0x35, 0x79, 0x92, 0x0d, 0xb7, 0x4d, 0x41,
	0x58, 0xc3, 0x0c, 0xc8, 0x4f, 0x4a, 0xe9, 0xe7, 0x97, 0xbe, 0xff, 0x98, 0xb4, 0x34, 0xc2, 0xdd,
	0xe1, 0x25, 0x52, 0x47, 0xb8, 0xfd, 0x5a, 0x66, 0xbc, 0xcf, 0xbd, 0x3e, 0x18, 0xe1, 0x0e, 0x58,
	0xbd, 0x7d, 0x03, 0x99, 0x2b, 0x13, 0xc7, 0x90, 0x48, 0x29, 0xd8, 0xfa, 0xd8, 0x51, 0x2e, 0xdc,
	0x63, 0xd6, 0x0b, 0xeb, 0x28, 0x79, 0xbd, 0x59, 0xd9, 0xa2, 0x4f, 0x2f, 0x70, 0x8d, 0xec, 0x95,
	0x5b, 0x8f, 0xfb, 0x32, 0xac, 0x2c, 0x3f, 0x3e, 0x54, 0xbf, 0xc6, 0xda, 0xab, 0x76, 0x97, 0x3f,
	0xe2, 0xf5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x90, 0x21, 0xdf, 0x98, 0x15, 0x01, 0x00, 0x00,
}
