// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RpcInfo struct {
	AppId  string `protobuf:"bytes,1,opt,name=AppId,json=appId" json:"AppId,omitempty"`
	ConnId uint64 `protobuf:"varint,2,opt,name=ConnId,json=connId" json:"ConnId,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=Token,json=token" json:"Token,omitempty"`
}

func (m *RpcInfo) Reset()                    { *m = RpcInfo{} }
func (m *RpcInfo) String() string            { return proto.CompactTextString(m) }
func (*RpcInfo) ProtoMessage()               {}
func (*RpcInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *RpcInfo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RpcInfo) GetConnId() uint64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *RpcInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RpcInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RpcRequest struct {
	Rid uint64 `protobuf:"varint,1,opt,name=Rid,json=rid" json:"Rid,omitempty"`
	// string AppId = 2;		//app唯一标识
	// uint64 ConnId = 3;
	// string UserId = 4;
	// string Token = 5;
	RpcInfo     *RpcInfo `protobuf:"bytes,6,opt,name=RpcInfo,json=rpcInfo" json:"RpcInfo,omitempty"`
	MessageType uint32   `protobuf:"varint,11,opt,name=messageType" json:"messageType,omitempty"`
	ProtoBuf    []byte   `protobuf:"bytes,12,opt,name=protoBuf,proto3" json:"protoBuf,omitempty"`
}

func (m *RpcRequest) Reset()                    { *m = RpcRequest{} }
func (m *RpcRequest) String() string            { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()               {}
func (*RpcRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *RpcRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *RpcRequest) GetRpcInfo() *RpcInfo {
	if m != nil {
		return m.RpcInfo
	}
	return nil
}

func (m *RpcRequest) GetMessageType() uint32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcRequest) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

type RpcResponse struct {
	Rid         uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc        string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	ConnId      uint64 `protobuf:"varint,4,opt,name=connId" json:"connId,omitempty"`
	MessageType uint32 `protobuf:"varint,11,opt,name=messageType" json:"messageType,omitempty"`
	ProtoBuf    []byte `protobuf:"bytes,12,opt,name=protoBuf,proto3" json:"protoBuf,omitempty"`
}

func (m *RpcResponse) Reset()                    { *m = RpcResponse{} }
func (m *RpcResponse) String() string            { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()               {}
func (*RpcResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *RpcResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *RpcResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RpcResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RpcResponse) GetConnId() uint64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *RpcResponse) GetMessageType() uint32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcResponse) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

func init() {
	proto.RegisterType((*RpcInfo)(nil), "pb.RpcInfo")
	proto.RegisterType((*RpcRequest)(nil), "pb.RpcRequest")
	proto.RegisterType((*RpcResponse)(nil), "pb.RpcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rpc service

type RpcClient interface {
	// Sends a greeting
	Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error)
}

type rpcClient struct {
	cc *grpc.ClientConn
}

func NewRpcClient(cc *grpc.ClientConn) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error) {
	out := new(RpcResponse)
	err := grpc.Invoke(ctx, "/pb.Rpc/Rpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rpc service

type RpcServer interface {
	// Sends a greeting
	Rpc(context.Context, *RpcRequest) (*RpcResponse, error)
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_Rpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Rpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Rpc/Rpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Rpc(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rpc",
			Handler:    _Rpc_Rpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x90, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0x3f, 0x37, 0x69, 0xfa, 0x75, 0x52, 0xfe, 0xc8, 0x42, 0xc8, 0xea, 0xca, 0x8a, 0x84,
	0xe4, 0x55, 0x90, 0xca, 0x09, 0x80, 0x55, 0xb6, 0xa3, 0x72, 0x80, 0xc6, 0x76, 0x51, 0x85, 0x88,
	0x07, 0x3b, 0x59, 0xb0, 0xe6, 0x1c, 0xdc, 0x15, 0xd9, 0x89, 0x02, 0xac, 0x59, 0x79, 0xde, 0x93,
	0x3d, 0xfe, 0xbd, 0x07, 0x6b, 0x4f, 0xba, 0x26, 0xef, 0x7a, 0xc7, 0x17, 0xd4, 0x56, 0x16, 0x56,
	0x48, 0xba, 0xe9, 0x8e, 0x8e, 0x5f, 0xc1, 0xf2, 0x9e, 0xa8, 0x31, 0x82, 0x49, 0xa6, 0xd6, 0xb8,
	0x3c, 0x44, 0xc1, 0xaf, 0xa1, 0x78, 0x74, 0x5d, 0xd7, 0x18, 0xb1, 0x90, 0x4c, 0xe5, 0x58, 0xe8,
	0xa4, 0xa2, 0xff, 0x14, 0xac, 0x6f, 0x8c, 0xc8, 0xd2, 0xf5, 0x62, 0x48, 0x2a, 0x6e, 0xd9, 0xbb,
	0x17, 0xdb, 0x89, 0x7c, 0xdc, 0xd2, 0x47, 0x51, 0x7d, 0x30, 0x00, 0x24, 0x8d, 0xf6, 0x6d, 0xb0,
	0xa1, 0xe7, 0x97, 0x90, 0xe1, 0x69, 0xfc, 0x28, 0xc7, 0xcc, 0x9f, 0x0c, 0xbf, 0x99, 0x39, 0x44,
	0x21, 0x99, 0x2a, 0x77, 0x65, 0x4d, 0x6d, 0x3d, 0x59, 0xb8, 0xf2, 0x13, 0xa3, 0x84, 0xf2, 0xd5,
	0x86, 0x70, 0x78, 0xb6, 0xfb, 0x77, 0xb2, 0xa2, 0x94, 0x4c, 0x9d, 0xe1, 0x4f, 0x8b, 0x6f, 0xe1,
	0x7f, 0x4a, 0xf7, 0x30, 0x1c, 0xc5, 0x46, 0x32, 0xb5, 0xc1, 0x59, 0x57, 0x9f, 0x0c, 0xca, 0x44,
	0x11, 0xc8, 0x75, 0xc1, 0x46, 0x0c, 0xff, 0x1b, 0x83, 0x43, 0xae, 0x9d, 0xb1, 0x29, 0xeb, 0x1a,
	0xd3, 0x1c, 0x3d, 0x63, 0x83, 0x9e, 0x72, 0xa6, 0x39, 0xa6, 0x1f, 0x7b, 0x48, 0x31, 0xbf, 0x5b,
	0xf9, 0x13, 0xdf, 0xee, 0x16, 0x32, 0x24, 0xcd, 0xd5, 0x78, 0x9c, 0x4f, 0x0d, 0x4c, 0xa5, 0x6d,
	0x2f, 0x66, 0x3d, 0xe2, 0x57, 0xff, 0xda, 0x22, 0x3d, 0xbd, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x17, 0x45, 0x6f, 0xf9, 0xd5, 0x01, 0x00, 0x00,
}
