// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateSessionRequest struct {
	Rid     uint64   `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	RpcInfo *RpcInfo `protobuf:"bytes,2,opt,name=rpcInfo" json:"rpcInfo,omitempty"`
	UserIds []string `protobuf:"bytes,11,rep,name=UserIds" json:"UserIds,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *CreateSessionRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionRequest) GetRpcInfo() *RpcInfo {
	if m != nil {
		return m.RpcInfo
	}
	return nil
}

func (m *CreateSessionRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type CreateSessionResponse struct {
	Rid       uint64 `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=Code" json:"Code,omitempty"`
	Desc      string `protobuf:"bytes,3,opt,name=Desc" json:"Desc,omitempty"`
	SessionId uint64 `protobuf:"varint,11,opt,name=SessionId" json:"SessionId,omitempty"`
}

func (m *CreateSessionResponse) Reset()                    { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()               {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *CreateSessionResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateSessionResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateSessionResponse) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type DeleteSessionUsersRequest struct {
	Rid           uint64   `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	RpcInfo       *RpcInfo `protobuf:"bytes,2,opt,name=rpcInfo" json:"rpcInfo,omitempty"`
	SessionId     uint64   `protobuf:"varint,11,opt,name=SessionId" json:"SessionId,omitempty"`
	DeleteUserIds []string `protobuf:"bytes,12,rep,name=DeleteUserIds" json:"DeleteUserIds,omitempty"`
}

func (m *DeleteSessionUsersRequest) Reset()                    { *m = DeleteSessionUsersRequest{} }
func (m *DeleteSessionUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSessionUsersRequest) ProtoMessage()               {}
func (*DeleteSessionUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *DeleteSessionUsersRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeleteSessionUsersRequest) GetRpcInfo() *RpcInfo {
	if m != nil {
		return m.RpcInfo
	}
	return nil
}

func (m *DeleteSessionUsersRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *DeleteSessionUsersRequest) GetDeleteUserIds() []string {
	if m != nil {
		return m.DeleteUserIds
	}
	return nil
}

type AddSessionUsersRequest struct {
	Rid        uint64   `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	RpcInfo    *RpcInfo `protobuf:"bytes,2,opt,name=rpcInfo" json:"rpcInfo,omitempty"`
	SessionId  uint64   `protobuf:"varint,11,opt,name=SessionId" json:"SessionId,omitempty"`
	AddUserIds []string `protobuf:"bytes,12,rep,name=AddUserIds" json:"AddUserIds,omitempty"`
}

func (m *AddSessionUsersRequest) Reset()                    { *m = AddSessionUsersRequest{} }
func (m *AddSessionUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*AddSessionUsersRequest) ProtoMessage()               {}
func (*AddSessionUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *AddSessionUsersRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *AddSessionUsersRequest) GetRpcInfo() *RpcInfo {
	if m != nil {
		return m.RpcInfo
	}
	return nil
}

func (m *AddSessionUsersRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *AddSessionUsersRequest) GetAddUserIds() []string {
	if m != nil {
		return m.AddUserIds
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSessionRequest)(nil), "pb.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "pb.CreateSessionResponse")
	proto.RegisterType((*DeleteSessionUsersRequest)(nil), "pb.DeleteSessionUsersRequest")
	proto.RegisterType((*AddSessionUsersRequest)(nil), "pb.AddSessionUsersRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Session service

type SessionClient interface {
	// 创建会话
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	DeleteSessionUsers(ctx context.Context, in *DeleteSessionUsersRequest, opts ...grpc.CallOption) (*Response, error)
	AddSessionUsers(ctx context.Context, in *AddSessionUsersRequest, opts ...grpc.CallOption) (*Response, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := grpc.Invoke(ctx, "/pb.Session/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) DeleteSessionUsers(ctx context.Context, in *DeleteSessionUsersRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.Session/DeleteSessionUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) AddSessionUsers(ctx context.Context, in *AddSessionUsersRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.Session/AddSessionUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	// 创建会话
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	DeleteSessionUsers(context.Context, *DeleteSessionUsersRequest) (*Response, error)
	AddSessionUsers(context.Context, *AddSessionUsersRequest) (*Response, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_DeleteSessionUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).DeleteSessionUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Session/DeleteSessionUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).DeleteSessionUsers(ctx, req.(*DeleteSessionUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_AddSessionUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSessionUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).AddSessionUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Session/AddSessionUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).AddSessionUsers(ctx, req.(*AddSessionUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Session_CreateSession_Handler,
		},
		{
			MethodName: "DeleteSessionUsers",
			Handler:    _Session_DeleteSessionUsers_Handler,
		},
		{
			MethodName: "AddSessionUsers",
			Handler:    _Session_AddSessionUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}

func init() { proto.RegisterFile("session.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x75, 0xdb, 0x62, 0xe9, 0xa4, 0x51, 0x19, 0x54, 0xb6, 0x41, 0xa5, 0x04, 0x85, 0x9c, 0x72,
	0xa8, 0x67, 0x0f, 0x25, 0x45, 0xc8, 0x75, 0xc5, 0x0f, 0x30, 0xdd, 0x11, 0x02, 0x92, 0x8d, 0xd9,
	0xf8, 0x1d, 0x5e, 0xfd, 0x31, 0xff, 0x47, 0x76, 0x37, 0xb1, 0x26, 0x46, 0x2f, 0x82, 0xb7, 0xd9,
	0xb7, 0xfb, 0xf6, 0xbd, 0x79, 0x33, 0xe0, 0x6b, 0xd2, 0x3a, 0x57, 0x45, 0x5c, 0x56, 0xaa, 0x56,
	0x38, 0x2a, 0xb3, 0xe0, 0xa0, 0x22, 0x5d, 0xaa, 0x42, 0x93, 0xc3, 0x02, 0xbf, 0x2a, 0xb7, 0x69,
	0xf1, 0xa8, 0xdc, 0x31, 0xcc, 0xe1, 0x38, 0xa9, 0xe8, 0xa1, 0xa6, 0x3b, 0xc7, 0x14, 0xf4, 0xfc,
	0x42, 0xba, 0xc6, 0x23, 0x18, 0x8b, 0x5c, 0x72, 0xb6, 0x64, 0xd1, 0x44, 0x98, 0x12, 0xaf, 0x60,
	0xda, 0x50, 0xf9, 0x68, 0xc9, 0x22, 0x6f, 0xe5, 0xc5, 0x65, 0x16, 0x0b, 0x07, 0x89, 0xf6, 0x0e,
	0x39, 0x4c, 0xef, 0x35, 0x55, 0xa9, 0xd4, 0xdc, 0x5b, 0x8e, 0xa3, 0x99, 0x68, 0x8f, 0xa1, 0x82,
	0x93, 0x9e, 0x94, 0x33, 0x36, 0xa0, 0x85, 0x30, 0x49, 0x94, 0x24, 0x2b, 0x34, 0x13, 0xb6, 0x36,
	0xd8, 0x86, 0xf4, 0x96, 0x8f, 0x1d, 0x66, 0x6a, 0x3c, 0x83, 0x59, 0xf3, 0x59, 0x2a, 0xb9, 0x67,
	0xf9, 0x3b, 0x20, 0x7c, 0x63, 0xb0, 0xd8, 0xd0, 0x13, 0x7d, 0x2a, 0x1a, 0x27, 0xfa, 0xcf, 0x1d,
	0xfe, 0x2a, 0x8a, 0x97, 0xe0, 0x3b, 0xcd, 0x36, 0x85, 0xb9, 0x4d, 0xa1, 0x0b, 0x86, 0xaf, 0x0c,
	0x4e, 0xd7, 0x52, 0xfe, 0xa3, 0xaf, 0x0b, 0x80, 0xb5, 0x94, 0x5d, 0x53, 0x5f, 0x90, 0xd5, 0x3b,
	0x83, 0x69, 0xf3, 0x1a, 0x6f, 0xc1, 0xef, 0x4c, 0x0a, 0xb9, 0x11, 0x1c, 0xda, 0x93, 0x60, 0x31,
	0x70, 0xe3, 0xc6, 0x1a, 0xee, 0x61, 0x02, 0xf8, 0x3d, 0x7f, 0x3c, 0x37, 0x94, 0x1f, 0xe7, 0x12,
	0xcc, 0x6d, 0x73, 0xbb, 0x4f, 0x6e, 0xe0, 0xb0, 0x97, 0x14, 0x06, 0xe6, 0xc9, 0x70, 0x7c, 0x7d,
	0x7a, 0xb6, 0x6f, 0xf7, 0xfc, 0xfa, 0x23, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x58, 0x40, 0xa4, 0x1b,
	0x03, 0x00, 0x00,
}
